a=input('Enter a letter\n')
b=input('Enter a letter\n')
c=input('Enter a letter\n')
d=input('Enter a letter\n')
print('The letters are',a,b,c,d)
a=chr(ord(a)+1)
b=chr(ord(b)+1)
c=chr(ord(c)+1)
d=chr(ord(d)+1)
print('The letters are now',a,b,c,d)